# Datasource
spring:
  datasource:
     url: jdbc:mysql://172.17.0.1:3306/empleados_simple

# Username and password
     username: maza
     password: maza

# Keep the connection alive if idle for a long time (needed in production)
     testWhileIdle: true
     validationQuery: SELECT 1

  application:
     name: empleados-service
      
server:
# Puerto aleatorio
#  port: ${PORT:0}
  port: 5555
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
 