# Datasource
spring:
  datasource:

### Descomentar si queremos usar la bd derby. Comentar la parte de mysql ###
#      driver-class-name: org.apache.derby.jdbc.ClientDriver
#      url: jdbc:derby://localhost//home/made/appData/derby-dbs/empleados

### Descomentar si queremos usar la bd mysql. Comentar la parte de derby ###

     url: jdbc:mysql://localhost:3306/empleados_simple
# Username and password
     username: maza
     password: maza

# Keep the connection alive if idle for a long time (needed in production)
     testWhileIdle: true
     validationQuery: SELECT 1

  application:
     name: empleados-service

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
# Generamos id aleatorio para poder registrar diferentes instancias con eureka
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
server:
# Puerto aleatorio
  port: ${PORT:0}
#  port: 5555
 
# Config propia
app:
  jwtSecretKey: P@tit0 
 