# Datasource
spring:
  application:
     name: empleados-service
      
server:
# Puerto aleatorio
#  port: ${PORT:0}
  port: 5555
  tomcat:
    max-threads: 400

org:
  apache:
    coyote:
      http2:
        Http2Protocol: 400 