# Datasource
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/empleados_simple

# Username and password
     username: maza
     password: maza

# Keep the connection alive if idle for a long time (needed in production)
     testWhileIdle: true
     validationQuery: SELECT 1

  application:
     name: empleados-service

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
# Para poder lanzar diferentes instancias
# (hay que modificar el server.port para cada instancia)
    instanceId=:
      
server:
  port: 5556
  
 