# Datasource
spring:
  datasource:
     url: jdbc:mysql://172.17.0.1:3306/empleados_simple

# Username and password
     username: maza
     password: maza

# Keep the connection alive if idle for a long time (needed in production)
     testWhileIdle: true
     validationQuery: SELECT 1

  application:
     name: empleados-service

eureka:
  client:
    enabled: true
    serviceUrl:
      # Al ejecutar desde docker activaremos EUREKA_SERVER así:
      # ENTRYPOINT ["java", "-DEUREKA_SERVER=http://eureka-service:1111/eureka","-jar","/empleados-rest-0.0.1-SNAPSHOT.jar"]
      defaultZone: ${EUREKA_SERVER:http://localhost:1111/eureka/}
#      defaultZone: http://eureka-service:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
# Generamos id aleatorio para poder registrar diferentes instancias con eureka
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
server:
# Puerto aleatorio
#  port: ${PORT:0}
  port: 4444
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
 