# Datasource
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/empleados_simple

# Username and password
     username: maza
     password: maza

# Keep the connection alive if idle for a long time (needed in production)
     testWhileIdle: true
     validationQuery: SELECT 1

  application:
     name: empleados-service

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
# Generamos id aleatorio para poder registrar diferentes instancias con eureka
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
server:
# Puerto aleatorio
#  port: ${PORT:0}
  port: 5555

management:
  endpoints:
    web:
      exposure:
        include: "*"

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  packagesToScan: profe.empleados.model

# Config propia
app:
  jwtSecretKey: P@tit0 

 